#!/usr/bin/env node
var express = require('express');
var mongo = require('./lib/db.js');
var auth = require('./lib/auth.js');
var cookieParser = require('cookie-parser');
mongo.connect()
mongo.init();
mongo.printAll();
// mongo.deleteAll();
// mongo.printAll();

var app = express();

var logAll = function(req, res, next) {
	if (req.headers.authorization) console.log(req.headers.authorization);
	next()
};

app.use(logAll);
app.use(cookieParser());
setInterval(auth.purgeAuth, 30000);


var fs = require('fs');

var authenticate = require('./routes/authenticate');
var resources = require('./routes/resources');
var download = require('./routes/download');

app.use('/error', function(req, res, next) {
    res.writeHead(404, 'Not Found', {'Content-Type': 'text/html'});
    fs.readFile('./webroot/error.html', {encoding: 'utf8'}, function(err, data) {
        if (err) throw err;
        res.end(data);
        });
});
app.use('/auth', authenticate);
app.use('/resources', resources);
app.use('/download', download);
app.use('/js', express.static('./webroot/js'));
app.use('/css', express.static('./webroot/css'));
app.use('/partials', express.static('./webroot/partials'));
app.use('/bower_components', express.static('./webroot/bower_components'));
app.all('*', function(req, res, next) {
    res.sendfile('./webroot/index.html');
    });

app.listen(8000);
