#!/usr/bin/env node
var express = require('express');
var mongo = require('./lib/db.js');
mongo.connect()
// mongo.init();
// mongo.printAll();
// mongo.deleteAll();
// mongo.printAll();

var app = express();

var logAll = function(req, res, next) {
	if (req.headers.authorization) console.log(req.headers.authorization);
	next()
};

app.use(logAll);

var fs = require('fs');

var auth = require('./routes/authenticate');
var main = require('./routes/main');

app.use('/error', function(req, res, next) {
    res.writeHead(404, 'Not Found', {'Content-Type': 'text/html'});
    fs.readFile('./webroot/error.html', {encoding: 'utf8'}, function(err, data) {
        if (err) throw err;
        res.end(data);
        });
});
app.use('/auth', auth);
app.use('/js', express.static('./webroot/js'));
app.use('/css', express.static('./webroot/css'));
app.use('/partials', express.static('./webroot/partials'));
app.use('/bower_components', express.static('./webroot/bower_components'));
app.all('*', function(req, res, next) {
    res.sendfile('./webroot/index.html');
    });

app.listen(8000);
